Update dotnet2.yml
test steps added

diff --git a/.github/workflows/dotnet2.yml b/.github/workflows/dotnet2.yml
--- a/.github/workflows/dotnet2.yml
+++ b/.github/workflows/dotnet2.yml
@@ -23,3 +23,11 @@ jobs:
       run: dotnet build --no-restore
     - name: Test
       run: dotnet test --no-build --verbosity normal
+      
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Spec Flow Tests       # Name of the check run which will be created
+        path: reports/dotnet-*.xml  # Path to test results
+        reporter: dotnet-trx        # Format of test results
